### ISSUE TITLE
`ContentProvider.requireContext()` requires API level 30

### ISSUE THREAD

**Issue by moneytoo** [alexbakker/webdav-provider#1]
Hi. Many thanks for your really useful documents provider. 👍 

As used in https://github.com/alexbakker/webdav-provider/blob/ad19a1b366ec1b59da8ce0ae91452c0f73ceaee8/app/src/main/java/me/alexbakker/webdav/provider/WebDavProvider.kt#L141 `ContentProvider.requireContext()` requires [API level 30](https://developer.android.com/reference/android/content/ContentProvider#requireContext()) there so it prevents the usage on API 23-29.

**Comment by alexbakker** [comment]
Thanks for letting me now! Strange that the linter didn't complain about this issue.

> Many thanks for your really useful documents provider. +1

I'm glad you like it! I have to admit that this isn't really ready for production use yet though. What are you using it for, if I may ask?

**Comment by moneytoo** [comment]
> What are you using it for, if I may ask?

I'm looking for document providers (WebDAV, SFTP, SMB) that I can both use and recommend other users. As a developer, users are asking for support for various protocols. I want to keep my apps light as well as to educate the users and "use it right" - if possible, use single document provider instead of embedding it in every possible app (and managing credentials in each app). This also allows creating creating network accessing apps without internet permission.

If you don't mind, I will submit few more issues that prevent me to use webdav-provider fully.

**Comment by alexbakker** [comment]
> This also allows creating creating network accessing apps without internet permission.

Interesting. This is exactly the use case I had in mind for this as well. I work on Aegis Authenticator and some of our users have requested the ability to back up to WebDAV, but we don't want to give Aegis the internet permission.

> If you don't mind, I will submit few more issues that prevent me to use webdav-provider fully.

Sure, it would be good to know about the issues that currently exist. I can't make any promises as to when or if I'll address them though.

**Comment by moneytoo** [comment]
> I can't make any promises as to when or if I'll address them though.

I fully understand. This goes without saying. I will just voice my feedback / document my experience. (BTW, it's crazy that's impossible to find any other app that does something similar, at least for WebDAV.)
