### ISSUE TITLE
what webdav servers has this been tested with?

### ISSUE THREAD

**Issue by aguaviva** [alexbakker/webdav-provider#13]
I am using sabredav and I am getting the following error:

![image](https://user-images.githubusercontent.com/5200915/146814799-2157bb46-c315-4dc4-b41d-ef9fff90b047.png)

I get the same result regardless of how "verify certificates" check box is.

The url to my webdav is something like this:
> https://myserver.duckdns.org:4430/sabredav/server.php
This url works fine with firefox and also with windows.

See the pic below for more details:

![image](https://user-images.githubusercontent.com/5200915/146815183-7a19e533-4486-4ca4-b756-46087d38f0da.png)

I'll be happy to debug this if you provide some help on where to start.

**Comment by alexbakker** [comment]
It looks like turning the "Verify certificates" option off doesn't do anything yet, so that could explain the issue if https://myserver.duckdns.org:4430/sabredav/server.php doesn't present a certificate signed by a trusted authority.

**Comment by aguaviva** [comment]
First off thanks for sharing this great project!! :)

As for the cert, maybe it could be that, although both firefox and chrome in windows/linux and android accept that certificate... (I used letsencrypt to create the certs.) 

It looks like the error is coming from retrofit2, I am trying to figure out how to step into that module.

**Comment by aguaviva** [comment]
I just noticed you added a HttpLoggingInterceptor and it outputs the following:

/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: --> PROPFIND https://myserver.duckdns.org:4430/sabredav
/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I am adding this here just for completeness and in case it may help others.

**Comment by aguaviva** [comment]
ok, here is the solution:   https://tsunderechen.gitlab.io/2020/04/nginx-ssl-certificate-fullchain-vs-cert/

In nginx I was serving cert.cer and not fullchain.cer

I hope this helps others!

**Comment by aguaviva** [comment]
This works like a charm! Everybody should use your app and have a shared folder in a rapsberry pi! :)

Thanks for sharing, this is amazing!!!
