### ISSUE TITLE
can't connect. error 405

### ISSUE THREAD

**Issue by EdvardBaldanov** [alexbakker/webdav-provider#20]
![Screenshot_20220621-105033_WebDAV Provider (Debug)](https://user-images.githubusercontent.com/104691755/174706072-090e6778-0b3e-416f-9fe4-48494bb50fe4.png)

**Comment by alexbakker** [comment]
If a ``PROPFIND`` on the root URL results in a 405, there's probably no WebDAV server running at that endpoint.
