### ISSUE TITLE
Accept custom root (top level directory) from url

### ISSUE THREAD

**Issue by moneytoo** [alexbakker/webdav-provider#3]
I have WebDAV shares (WebDAV server in Apache reverse proxied using nginx) that are accessed like `example.com/webdav/`. In this case, the root (topmost directory) should be `/webdav/`. Webdav-provider always uses `/` instead of the path from url.

(I was able to use my share after trying to hardcode custom root. I'm not sure if I will be able to provide high quality PR though.)

**Comment by alexbakker** [comment]
Agreed. I actually thought this was already supported, but that appears to not be the case after a quick test.
