### ISSUE TITLE
URL decode file display names

### ISSUE THREAD

**Issue by moneytoo** [alexbakker/webdav-provider#5]
File display names should probably be URL decoded

https://github.com/alexbakker/webdav-provider/blob/2786cce446a750e9788f309800778153738e6f13/app/src/main/java/me/alexbakker/webdav/provider/WebDavProvider.kt#L300

possibly using something like

```
add(Document.COLUMN_DISPLAY_NAME, URLDecoder.decode(file.name, StandardCharsets.UTF_8.name()))
```

because without decoding it looks like this:

<img src="https://user-images.githubusercontent.com/1071643/119731426-3684f180-be77-11eb-9988-e749299b103c.jpg" width="200"/>

After decoding:

<img src="https://user-images.githubusercontent.com/1071643/119731439-3b49a580-be77-11eb-80ba-212c7f769960.jpg" width="200"/>

**Comment by alexbakker** [comment]
Agreed.
