### ISSUE TITLE
OutOfMemoryError when copying ≈ 350 MB file

### ISSUE THREAD

**Issue by moneytoo** [alexbakker/webdav-provider#6]
I'm getting `OutOfMemoryError`s when trying to copy/download 350 MB large file (using the stock Android Files app). 

```
me.alexbakker.webdav W/exbakker.webda: Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 5961784 free bytes and 5822KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 0 bytes)" (VmSize 5422796 kB, recursive case)
```

I'm able to copy the same file using other documents providers (Google Drive, Dropbox, Samba) on OnePlus 7 device (8 GB RAM).

**Comment by alexbakker** [comment]
What happens if you comment out the following lines?

https://github.com/alexbakker/webdav-provider/blob/2786cce446a750e9788f309800778153738e6f13/app/src/main/java/me/alexbakker/webdav/provider/WebDavClient.kt#L50-L54

**Comment by moneytoo** [comment]
Great, seems like that's it - no more OutOfMemoryError after commenting out the lines.

**Comment by alexbakker** [comment]
It would probably be good to have an in-app toggle for that, as the HTTP logger is useful while debugging. Apparently Retrofit tries to keep the full response body in-memory even though it doesn't print it if it's larger than a couple of kilobytes)
